name: Node.js Package

# From: https://dev.to/joeattardi/how-to-publish-an-npm-package-to-npm-and-github-package-registry-simultaneously-using-github-actions-213a
#
# Tag the commit
#    git tag 2.0.1
# Then I push this tag:
#   git push origin 2.0.1
#
# This will draft a new release in the repository, but it won't run the workflow yet.
# Go to your GitHub repository page and navigate to the releases section.
# You'll see the tag you just pushed at the top of the list.
#
# Click on the tag, then click the "Edit tag" button. Enter some details about the release,
# then click the green "Publish release" button. Once the release is published, the package
# publishing workflow should begin. To verify this, go to the "Actions" tab of your repository.
# You should see the "Node.js Package" workflow running.

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v1 (v1.2.0) = 50fbc622fc4ef5163becd7fab6573eac35f8462e
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      # actions/setup-node@v1 (v1.3.0) = b6651e20e530d6e6b845a9828606779e89f5529c
      - uses: actions/setup-node@b6651e20e530d6e6b845a9828606779e89f5529c
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v1 (v1.2.0) = 50fbc622fc4ef5163becd7fab6573eac35f8462e
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      # actions/setup-node@v1 (v1.3.0) = b6651e20e530d6e6b845a9828606779e89f5529c
      - uses: actions/setup-node@b6651e20e530d6e6b845a9828606779e89f5529c
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
